### ISSUE TITLE
Missing json file for Matsuribayashi patch

### ISSUE THREAD

**Issue by DogLover314** [07th-mod/python-patcher#101]
Installing the Matsuribayashi patch with the 1.1.34 version of the python patcher does not create an installedVersionData.json file in the game directory.

[MOD-INSTALLER-LOG-2020-05-24_15-45-04.txt](https://github.com/07th-mod/python-patcher/files/4674303/MOD-INSTALLER-LOG-2020-05-24_15-45-04.txt)

**Comment by ooa113y** [comment]
Fixed in 1953283.
