### ISSUE TITLE
Error: 406 Not Acceptable / Can't access 07th-mod website

### ISSUE THREAD

**Issue by Lostosaurus** [07th-mod/python-patcher#102]
I cannot access any part of the 07th-mod.com website. When I try to download the installer tries to download files from the website, but cannot and fails to install. Is anyone else familiar with this issue? I've never heard of a 406 error.

----- BEGIN EXECUTING COMMAND: [./aria2c --file-allocation=none --continue=true --retry-wait=5 -m 0 -x 8 -s 8 -j 1 --auto-file-renaming=false --allow-overwrite=true --follow-metalink=false --disable-ipv6=true -d C:\Users\****\AppData\Local\Temp\tmptmj817by https://07th-mod.com/Beato/Umineko-Voices-nsa.7z.meta4] -----

06/07 18:19:08 [[1;32mNOTICE[0m]
 Downloading 1 item(s)

06/07 18:19:09 [[1;31mERROR[0m]
 CUID#7 - Download aborted. URI=https://07th-mod.com/Beato/Umineko-Voices-nsa.7z.meta4
Exception: [AbstractCommand.cc:351]
 errorCode=22 URI=https://07th-mod.com/Beato/Umineko-Voices-nsa.7z.meta4
  -> [HttpSkipResponseCommand.cc:240]
 errorCode=22 The response status is not successful. status=406

06/07 18:19:09 [[1;32mNOTICE[0m]
 Download GID#a0c4945520236f96 not complete:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
a0c494|ERR |       0B/s|https://07th-mod.com/Beato/Umineko-Voices-nsa.7z.meta4

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

**Comment by drojf** [comment]
> I cannot access any part of the 07th-mod.com website

Are you in Japan? Japan is blocked from downloading (although the installer should warn you about this and prevent the installer starting up, if it doesn't, we need to fix that.)

We have a FAQ on it, but you can't access it without a VPN:

> If you cannot access these websites on any computer or phone (on local wifi, NOT mobile internet) that you try:
> 
>    - you may have a government firewall blocking access to the above websites.
>    - you might be in Japan (we currently don't allow downloads from Japan for legal reasons).
>    - an ISP/company/government firewall blocking access to the above websites.
> 
> To fix these issues, we suggest using a free VPN, such as https://protonvpn.com/ (do not use with P2P software) or https://www.vpngate.net (harder to use). This will bypass any external blocking of the above websites.

**Comment by Lostosaurus** [comment]
Hello, yes I am currently in Japan. I recently downloaded the game from Steam. I checked and my VPN was not running properly. I've reinstalled it and it appears to be working properly. Thank you for the assistance!

**Comment by drojf** [comment]
OA suggested switching the http error code to 451: "HTTP 451 Unavailable For Legal Reasons" so it's more clear why you can't access the website

If it's easy, I would suggest adding a custom error page (similar to video websites when it says "This content is not available in your country") for the main website and the 07th-mod wiki, and then 451 error for all other content so it causes the installer to error out.

**Comment by ooa113y** [comment]
I'd rather not have the error page have actual instructions on it, if we do go this route, as having easy-to-follow workarounds is the same as removing the block entirely.

**Comment by ItaloKnox** [comment]
I agree. I've debated for a long time on removing the block/making it a custom page (I actually should it somewhere in my PC), but there's a chance, even if small, that we can stay under the radar because the website might look offline.
