### ISSUE TITLE
Incorrect "Confirm Exit" popup placement when trying to close installer

### ISSUE THREAD

**Issue by miere43** [07th-mod/python-patcher#125]
1. Run `07th-Mod.Installer.Windows.exe`
2. Press `Run Installer`
3. Wait for browser/installer to load
4. Minimize installer window (**not the browser**)
5. Close window using taskbar:
![image](https://user-images.githubusercontent.com/3995549/97920661-d3146480-1d6a-11eb-9806-1afe28fa7fd0.png)
6. Unminimize installer window
7. Close installer popup is placed in top-left corner and is very small:
![image](https://user-images.githubusercontent.com/3995549/97920803-0c4cd480-1d6b-11eb-8812-2462b21f3fc9.png)

Expected result:
![image](https://user-images.githubusercontent.com/3995549/97921393-f12e9480-1d6b-11eb-9716-b9d7fa3f47f2.png)

Bug only happens when window is minimized, doesn't happen if window is in the background.

One way to fix the problem is to call [SetForegroundWindow ](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow) on installer window after user executes step 5, then enqueueing popup display to the next IMGUI frame.

**Comment by drojf** [comment]
Thanks for reporting this! I ended up doing what you said, and it seems to work without having to queue the popup for on the next frame.
