### ISSUE TITLE
Implement proper mod updating

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#13]

**Comment by ItaloKnox** [comment]
A bit later than promised but here it is:

The update system I have in mind works based on just comparing information from a local and remote version of the same file. During the installation of the patch, the installer will pull a json file from the patch repository (e.g. Onikakushi), which symbolizes you getting the latest version at the time of installation. This file would be placed inside the game folder, right at the root and stay there as long as the patch is installed.

Using Onikakushi as an example, this file would have each piece of the patch listed with their version. In this case, these:

* Patch = 6.1.0
* Graphics = 1.0.0
* Steam graphics = 1.0.0
* Voice = 1.0.0
* Movies = 1.0.0
* UI = ``X.Y.Z`` / ``platform`` (mac/linux/windows)


A few points to consider:

* ``Patch`` should be the only category starting at its real version. Everything else should start at 1.0.0 since no version tracking is kept for these.
* At least for Higurashi, there is no reason to automatically update the remote json. This can be kept manually.
* The UI mod should be a little trickier to keep updated. I suggest writing the user version during installation and then just compare the local json with the local sharedassets file. If they mismatch, pull the new version from our server (current UI linking method should make this easy).

So, recap:

1. user installs the patch. v6.1.0 is used in the patch, everything else is 1.0.0
2. new update is released, user checks for updates
3. installer checks local vs remote json (that can be kept into single JSON for each game repository or a big json with all games)
4. installer queues updates for every version that is greater than local versions listed
5. finally, installer checks if the UI mod can handle the update by comparing the local json with the local sharedassets
6. a final list of updates are generated, the files downloaded and installed and a new json replaces the local version

I'm not sure if this sounds really confusing because it makes a lot of sense in my head, if there's anything I should explain better, please let me know so I can elaborate.

**Comment by drojf** [comment]
I do understand everything I think. My main question is whether the remote version information should be kept in each repository, or in the existing `installData.json` file.

If you're updating it manually, it's probably easiest (from a human perspective) to have a separate version file in each repository, since you normally only edit the version number, and don't have any chance to mess up the `installData.json` file by accident.

The main issue with keeping it separate is keeping everything synchronized - if you change a URL, add or delete a file etc, you need to update both the `installData.json` file and the version file in the repository. However, if we assume that you normally only change the version and don't adjust anything else, this isn't a problem.

I was initially leaning towards keeping everything in the `installData.json` file, but now I've somewhat talked myself out of it, so I would go ahead with your method as is (one version file per repository).

**Comment by ItaloKnox** [comment]
I think that a single json for all chapters might be easier to manage, but I would prefer if it was separate from the ``installData.json`` file. However, if keeping one file for each repo would be easier to implement (e.g. less work to create local versions), I have nothing against it. It would be slightly troublesome when pushing updates for all Higurashi chapters at the same time, which seems to be happening often recently, but it's definitely not impossible or a major drain in the workflow. Pushing the update feature forward is more important than an extra step when pushing updates.

**Comment by drojf** [comment]
I got something working, but there were a few issues to work out which I've mostly resolved.

I'll briefly dump my brain of these issues here so there's some record of it, but it's not necessary to read it.

- handling file overrides in addition to normal files - Since the file overrides have the same "name" as the normal "files", it's a little difficult to specify their version in the version file. I solved this by addding an additional field in the installData.json so that all file overrides have unique ids. You can then use the "id" field to specify which file you are setting the version for in the version file. 
- handling dependencies. the "script" must always be added after the other packs. therefore if you say, update the "graphics" pack, and the script contains an updated graphics file, even if you have the 'current' script pack, you shouuld re-install the script pack ontop of the graphics pack. I solved this by using the "priority" field of the installData.json to decide if a dependency is required, (install all packs with higher priority, even if they weren't updated)
- handling different submods: For higurashi, you currently only have one submod, called "full". In the central `versionData.json` file containing the version information for all games, I allocated space for different submods, so you can specify which submod you are setting version for, with a string like `Onikakushi Ch.1/full`, `Onikakushi Ch.1/voice-only`. Umineko will definitely use these, but higurashi may never use them.
- Considering only the version for updating (not thinking about dependencies), there are 4 update cases:
	- There is no previous local version info - do full update as no version file exists on disk
	- The previous install was a different submod (for example, installing 'full' onto 'voice-only') - do full update
	- The file is not at all installed. This will trigger on UI mods of different versions, an unmodded game, or when you add a new file to an existing mod - update that file and any dependencies
	- The remote version of the file does not match. - update that file and any dependencies
- mod options handling: This issue hasn't really been resolved. I can add in some versioning for them later, but the main issue is whether the mod options overwrite files in the game directory or not (the dependencies thing). In the mean time, mod options will just always install

I still need to do a little more testing, but even then, I'll hold off until the new higurashi chapter has been released and everything's cooled down before attempting to release this updater feature. 

I would also like to add a little display which tells you what you're about to download/update before you start the install (shouldn't take that long, but it's not at all in the installer right now). 

I'm working off this repo for testing purposes: https://github.com/drojf/python-patcher

**Comment by drojf** [comment]
I tried to summarize how the installer currently works from a couple different angles...it ended up incredibly long. Might be a good idea to just skim over it then ask any questions in discord.

----

The installer currently works as follows

- The user begins an install of any game
- The installer downloads the `versionData.json` file from the git repository. This contains the version numbers of each file and file override for every mod.
- The installer will compare the versions in the remote `versionData.json` to the local `installedVersionData.json` file which is saved in the target install folder. Only the files whose versions have changed are updated.
- When the installer finishes, the updated versions are written to the the target install folder (the game folder)

Example
- User begins install of Onikakushi Ch.1
- Installer downloads `versionData.json`, looks up the `Onikakushi Ch.1/full` field.
- Installer compares versions with the `steamapps\common\Higurashi When They Cry\installedVersionData.json` file
- It would detect the `graphics` pack version is different (`1.0.0` -> `1.0.1`)
- Because the `graphics` pack updated, the `script` needs to be re-installed to (as the `script` is always applied ontop of the graphics patch)
- The installer will then display which packs need to be installed, and the user can start the install
- When the install is finished successfully, the `steamapps\common\Higurashi When They Cry\installedVersionData.json` is overwritten with the new version information.

----

End User's perspective:

- Currently the end user must "know" when there is an update - there's no launcher or anything which will automatically check for updates. I suppose we could use the "News" part of the installer to notify, but at that point they might as well just visit our website/wiki to check for updates.
- The user would then do an "install" of the game they want to update as if they were going to re-install the game
- Before they hit "Start Installation" a list of files which will be downloaded/installed will be shown. If they are updating, only the files which have been updated will be listed
- Hitting "Start Installation" will begin the update (which is the same as a normal installation, except only some of the files are installed)

If the user wants to perform a full install regardless, there is a button labelled "Advanced Version Options" which lets you delete the local version information/treat it as a fresh install.

Developer's Perspective:

- Add new files to the server
- In the git repository, modify the `installData.json` with new files and `versionData.json` with new versions

----

There is a problem which can occur here if the developer overwrites an existing file and then a user installs the patch:

- file A is set to version 1.0
- developer overwrites file A-1.0 with file A-1.1
- user installs this A-1.1, but version information still says A-1.0
- developer sets file A to version 1.1

When this happens, the user could be stuck with the wrong version of the file. You could avoid this by:

- file A is set to version 1.0
- developer deletes the file A-1.0
- user tries to install A-1.0 but it has been deleted, so install will fail
- developer sets file A to version 1.1
- developer overwrites file A-1.0 with file A-1.1
- user can then try to install again

You can also avoid this by always creating a new file name, rather than overwriting the old file.

----

Other notes:

- mod options are currently not versioned, and are always installed
- The UI mods etc. are handled by having a version for each individual UI mod, and then treating them the same as any other file.
- The download sizes of each file are cached to a file called `cachedDownloadSizes.json`, otherwise it would take too long to retrieve the file sizes of each file (with the way we currently do it). It is updated by travis, but can also be updated manually. Potentially this complication could be removed by retrieving file sizes in parallel.
- For testing, if you run the installer from a cloned git repository, it will read the `installData.json` and `versionData.json` from disk. The real installer has these files missing, so will download them from the remote git repository

There are some edge cases not above, like:

- when you install a mod partially, then change to a different mod, a full install should be peformed. This is handled by remembering what the last attempted install was, and if changed a full install is peformed.
- if the local version information is missing, I just do a full install
- if the remote version information for a mod is entirly missing, I treat that as an error. If only part of the information is missing, I think it just forces a full install of the files which are missing version information

**Comment by drojf** [comment]
The updating system has been in place for some time without issue, so I'm closing this now.
