### ISSUE TITLE
Update BGM/SE options in installer

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#139]
Previously, we had the BGM/SE fix applied by default, with no option to use the april update bgm/se. People requested the april update bgm/seback, so the option was added back (by me), but probably not in the best way.

Our installer options for the BGM/SE looks like this:

![installer options 1](https://user-images.githubusercontent.com/1249449/106552367-51032a00-656b-11eb-82e2-e716c5a6053b.png)

It should probably have the fix by default, like this:

![installer options 2](https://user-images.githubusercontent.com/1249449/106552410-6b3d0800-656b-11eb-9fa8-5a2b59c0da12.png)

But there are other changes to consider like updating the title, description. Also as italo mentioned:

> Another option is to take that section away entirely and just add the bgm/se April update in the optional section, together with the ost remake

That option sounds reasonable to me, but we need to make it very clear in the wiki and in the installer that our mod comes with the BGM/SE patch by default, as it's currently not documented anywhere except for the FAQ and in our current installer option itself.

Personally I prefer the explicit option version (the second image above) as it's the most clear to me (the text could be updated though).

**Comment by drojf** [comment]
Here is the current text in text form, so you can edit it easier:

BGM Fix

Attempts to fix some of the problems with the April BGM/SE Update - See the wiki for more details. The method used was:

- If the BGM/SE was replaced with an entirely different one, we have reverted it
- If the BGM/SE was replaced with a similar one, we use the new version


Restore April Update

Re-applies the april update BGM. Use this if you previously applied the BGM fix, but want to go back to the april update BGM.

**Comment by ItaloKnox** [comment]
Okay, so a couple of suggestions on how to handle this:

### The BGM/SE 2-option route

#### BGM Options
* [x] Original BGM
    Enable the original music from the japanese version of the game. This option was previously known as "BGM fix" and is now installed by default.
* [ ] New BGM
    Enable the new BGM introduced by MangaGamer in the April 2019 update.

This change capitalizes into rewriting how the fixes are presented, making the choice less about "right" or "wrong" and more about user choice.


### The optional download route

Like you said, that one would require extra clarification, and I feel like it won't be enough. It seems to be very common for people to join our Discord before reading the wiki, even though that would actually take *longer*. I would only go with that route in case the previous one isn't enough.

**Comment by drojf** [comment]
> The BGM/SE 2-option route

sounds good to me, but are you sure you want to remove the link to the wiki? It currently links to this page: https://07th-mod.com/wiki/Higurashi/FAQ/#what-was-the-april-update

**Comment by ItaloKnox** [comment]
Oh, I didn't even think about that. We should leave it in, I'm sure that will save the trouble of linking it on Discord every time someone asks about it.

Maybe change the option to:
> Enable the new BGM introduced by MangaGamer in the April 2019 update. [Learn more about the April update](https://07th-mod.com/wiki/Higurashi/FAQ/#what-was-the-april-update).

**Comment by drojf** [comment]
OK, currently have this:

![image](https://user-images.githubusercontent.com/1249449/106695050-e666f280-662d-11eb-9a2e-fcbc677fef2f.png)

all good?

**Comment by ItaloKnox** [comment]
Looks great!
