### ISSUE TITLE
Higurashi (umineko?): Add Version check before installing

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#15]
If possible, add a version check, as the mod might not work properly on older versions of the game(s).

Otherwise, remind user to update their game to the latest version, if they have an old version of the game.

**Comment by drojf** [comment]
This is implemented for Higurashi only as of release 0.0.7 https://github.com/07th-mod/python-patcher/tree/v0.0.7

**Comment by ooa113y** [comment]
This is basically implemented as far as it's important for Umineko in 8d65725.
