### ISSUE TITLE
Add note that Console arcs *might not* work on MacOS

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#150]
We had a report (just one) that the console arcs do not work on MacOS - the game would crash immediately, even before anything can happen (steam hima ep4).

went through all the usual things, so I don't think it's any of the usuall issues. 

should ask users to give feedback if the chapter works for them on MacOS

**Comment by tellowkrinkle** [comment]
CNR with macOS 11.3.1 (20E241), GOG Hima based on Unity 5.4.1f1, latest patch installed with the installer

**Comment by drojf** [comment]
Thanks Tellow, I guess I'll hold off any action for now.

I'll leave this issue open in case we get more reports, though, to keep track of the problem.
