### ISSUE TITLE
Add "Custom" installation option

### ISSUE THREAD

**Issue by ItaloKnox** [07th-mod/python-patcher#16]
All Higurashi patches (except the console arcs) can make use of this option after the recent update that changed all the audio in the game. The process is simple: just take the full patch installation and let the user select certain checkboxes that will add extra downloads during installation. For now, this update should only apply to audio, but it may need to change from checkboxes to checkboxes **and** radio buttons for add-ons that cannot work together. The easy way to do this is to separate certain add-ons in categories and not have them interact with each other.

Example:
* [x] Audio rollback
    * Restores all new audio to legacy audio
* [x] ItaloKnox OST remake
    * Updates the OST with remakes for certain tracks (together they work nicely since it only replaces a slice of the other)

One more:
* [x] Anime OST
* [ ] Console OST
    * (greyed out)
* [ ] Audio rollback
    * (greyed out)
* [x] ItaloKnox OST remake

^ you can pretty much get the gist of it. Full replacements should not interact with full replacements, only incremental add-ons or partial replacements.

**Comment by drojf** [comment]
I think we could add the options to the JSON config file, then have the installer generate the checkboxes in the GUI, as appropriate, by adding another section (called "modOptions")

See here for an example:

https://gist.github.com/drojf/3eb17ff5e7da21cac6fd83b74b8dc6f1 (NOTE: I didn't quite know which ones you wanted to be radio buttons/checkboxes, but the JSON should be expressive enough you can describe any combination you want)

I'm assuming these options apply to both the "voice only" and "full patch" subMods - if they're different you'd need to specify them for each subMod.

I would make the installer look for the "OST Options" section in the JSON config file, then do whatever is necessary with these options after the user has selected them. For the OST options, it would just extract the archive file into the root game directory (tell me if you want to extract to a directory other than root)

**Comment by ItaloKnox** [comment]
Here are the files, descriptions and some instructions on how the installer should handle them:

# Install instructions
All downloads should install **exclusively** inside ``StreamingAssets``. The order is ``radio button`` downloads installs first, ``checkmark`` downloads installs second (in any order in case there are multiple downloads).

# Further information
The initial release should only contain the old OST as the radio button (single choice) downloads and my OST remakes as the checkmark buttons. We will add more in the next cumulative release for the main patch.

## Higurashi (Question Arcs - Ch.1 ~ 4 only)
[Higurashi-OldBGM.7z](http://07th-mod.com/rikachama/audio/Higurashi-OldBGM.7z)
- Restores the music tracks from the original release (pre-2019)

[Higurashi-OldSE.7z](http://07th-mod.com/rikachama/audio/Higurashi-OldSE.7z)
- Restores the sound effects from the original release (pre-2019)

## Higurashi (Answer Arcs - Ch.5 ~ 8 only)
[HigurashiKai-OldBGM.7z](http://07th-mod.com/rikachama/audio/HigurashiKai-OldBGM.7z)
- Restores the music tracks from the original release (pre-2019)

[HigurashiKai-OldSE.7z](http://07th-mod.com/rikachama/audio/HigurashiKai-OldSE.7z)
- Restores the sound effects from the original release (pre-2019)

## Additional downloads (Question Arcs - Ch.1 ~ 4 only)
[Higurashi.OST.Remake.zip](http://07th-mod.com/misc/Higurashi.OST.Remake.zip)
- Handmade remakes of several music tracks from the original release (pre-2019)
    - [Audio samples here](https://radiataalice.bandcamp.com/album/hinamizawa-syndrome-vol-1)

[**Note for @drojf:** the link is still unpublished. It will work after we push the release.]

Be free to rework the descriptions or format them any way you want.

**Comment by drojf** [comment]
@ItaloKnox can this issue be closed now? Or is there still some stuff which is missing?

**Comment by ItaloKnox** [comment]
Looks good!
