### ISSUE TITLE
Higurashi Autodetect on MacOS

### ISSUE THREAD

**Issue by FatesTimelines1337** [07th-mod/python-patcher#198]
When using the installer for MacOS, the autodetected path for a HigurashiEpX.app is listed twice. As far as I can tell both paths are exactly the same.

**Comment by drojf** [comment]
Can you send the install logs? Should be a `07th-mod-logs.zip` file in your browser downloads

**Comment by FatesTimelines1337** [comment]
[MOD-INSTALLER-LOG-2023-02-25_18-03-09.txt](https://github.com/07th-mod/python-patcher/files/10832573/MOD-INSTALLER-LOG-2023-02-25_18-03-09.txt)

**Comment by drojf** [comment]
Hi, can you try this new version, and see if it fixes it?

Please ignore the "a new installer version is available" message.

[07th-Mod.Installer.mac.zip](https://github.com/07th-mod/python-patcher/files/10832893/07th-Mod.Installer.mac.zip)

**Comment by FatesTimelines1337** [comment]
Yes, only one path was found

**Comment by drojf** [comment]
ah great, seeing as it works I've released it as a new installer: https://github.com/07th-mod/python-patcher/releases/tag/v1.2.10

Please reopen this issue if you still have this issue on the new installer, when you install the next chapter's mod
