### ISSUE TITLE
Steam Grid on MacOS

### ISSUE THREAD

**Issue by FatesTimelines1337** [07th-mod/python-patcher#201]
The Steam grid path on MacOS is the following

`~/Library/Application Support/Steam/userdata/[STEAMID]/config/grid`

**Comment by drojf** [comment]
afaik just gotta add an extra case for MacOS here, which always returns the path `~/Library/Application Support/Steam` (unless there are any other possible locations on MacOS)

https://github.com/07th-mod/python-patcher/blob/beb5ea30240a278ff86347a3e5073092a5cb462e/steamGridExtractor.py#L9-L32

**Comment by drojf** [comment]
@FatesTimelines1337 Can you see if this installer installs the steamgrid?

You can just re-run an install on any chapter and it should install the steamgrid files.


[07th-Mod.Installer.mac(2).zip](https://github.com/07th-mod/python-patcher/files/10947546/07th-Mod.Installer.mac.2.zip)

**Comment by FatesTimelines1337** [comment]
I don't see the option to install the steamgrid

**Comment by drojf** [comment]
ah, I forgot about that part...gimme a minute

**Comment by drojf** [comment]
@FatesTimelines1337 try this version
[07th-Mod.Installer.mac(3).zip](https://github.com/07th-mod/python-patcher/files/10947590/07th-Mod.Installer.mac.3.zip)

**Comment by FatesTimelines1337** [comment]
[MOD-INSTALLER-LOG-2023-03-10_23-33-16.txt](https://github.com/07th-mod/python-patcher/files/10947611/MOD-INSTALLER-LOG-2023-03-10_23-33-16.txt)

steamgrid did not extract

**Comment by drojf** [comment]
ahh sorry I think I know what I did wrong. I'll also print out some info in case it still doesn't work

**Comment by drojf** [comment]
please try this version
[07th-Mod.Installer.mac(4).zip](https://github.com/07th-mod/python-patcher/files/10947650/07th-Mod.Installer.mac.4.zip)

**Comment by FatesTimelines1337** [comment]
Everything looks good to me

**Comment by drojf** [comment]
Should be fixed as of https://github.com/07th-mod/python-patcher/releases/tag/v1.2.13
