### ISSUE TITLE
Wrong UI applied when language patch used (Chapter 5 - Pink font in French Version)

### ISSUE THREAD

**Issue by IrealiTY** [07th-mod/python-patcher#202]
Playing on steam deck. 
Installing the English patch works flawless but installing the french version results in all the text being pink boxes.

**Comment by drojf** [comment]
I think all the issues mentioned in this thread are fixed or no longer relevant:

- The Ch.5 pink text bug is fixed
- The issue with switching between proton and native might no longer be needed:  https://github.com/07th-mod/python-patcher/issues/200
- My Ch.8 fix actually had some sort of problem, but I fixed it properly recently here: https://github.com/orian34/matsuribayashi/issues/9
