### ISSUE TITLE
Taskbar icon disappears on Windows 11 as soon as WebView opens

### ISSUE THREAD

**Issue by andOlga** [07th-mod/python-patcher#209]
When the launcher first boots up, the taskbar icon shows correctly (the "cute" Rena face).

When the webview opens, the icon vanishes and is replaced with this weird transparent "box" that's barely even visible (and *completely* invisible when it's not selected).

![image](https://user-images.githubusercontent.com/462484/230714366-ea8a9a75-dac0-48f5-9de0-261f4ed0f281.png)

I'm not completely sure, but I don't believe the installer used to do this in the past (even with the webview). I remember seeing the icon appear correctly before.

**Comment by drojf** [comment]
I just checked on my Windows 10 computer and it seems to work OK, I guess it's just Windows 11? 

I'll double check on my Windows 11 computer later.

![image](https://user-images.githubusercontent.com/1249449/230715657-530274ba-8ca0-4315-8112-a48720bf2615.png)

**Comment by drojf** [comment]
Strange, I tested on my Windows 11 laptop and it still seems to work OK.

Can you try copying it into an empty folder and running it from there? In the past I had some issues with windows doing some icon caching (although to my understanding, the way the icon is set for the webview shouldn't be cached).

I could also ask some people on discord to see if they have the same issue

**Comment by andOlga** [comment]
> Can you try copying it into an empty folder and running it from there?

That didn't do anything. But if it's an issue just on my side then it's no big deal.

**Comment by andOlga** [comment]
This seems to have resolved itself after a Windows update, seems to have been an OS build-specific bug. Closing.
