### ISSUE TITLE
Add an option to keep temporary downloads after install

### ISSUE THREAD

**Issue by 13xforever** [07th-mod/python-patcher#210]
This is useful for people like me who's too lazy to do full manual install but wants to keep backups of source mod files for future use/offline install.

There's already all the needed pieces in place except for a new UI checkbox for higurashi series.

**Comment by drojf** [comment]
I've published a new release (v1.2.15) which has the "keep downloads" option added to the HIgurashi games: https://github.com/07th-mod/python-patcher/releases

You don't have to test it, but if you do end up testing it, let me know if it works.

**Comment by 13xforever** [comment]
yeah, looks about how I thought to do it, but I just hardcoded the option locally for now, and it worked fine for me

thanks!
