### ISSUE TITLE
Add Umineko warning interstitial

### ISSUE THREAD

**Issue by andOlga** [07th-mod/python-patcher#212]
We have talked about this over Discord a while ago, but I wanted to leave a full record of this here so that it's not (completely) forgotten.

The current install experience for our Umineko patches directs users to play the console version of the game instead, with the English fan translation patch for it, as it has extra features/content that we don't (and, in some cases, *can't*) support in the 07th-Mod patches for the games.

However, the warning isn't overly visible. It only shows up after a submod is selected (i.e. after a user has already expressed their intention to go through with the install of 07th-Mod), and even though it's the first thing on the page, it's buried within walls of other documentation text that is likely to be ignored just due to the sheer amount of it.

My suggestion would be, when any of the Umineko patches are selected, to first direct users to a complete page that houses the alternate recommendation. Beneath the text could be two buttons along the lines of "Open console patch website" and "Continue with PC patch install" or whatever. It being a complete page would also allow to add a detailed breakdown of all the features and requirements of the two versions.

I'm ready to contribute the HTML for the actual warning text and the comparison etc, but I lack sufficient Vue knowledge to create the functionality to display such a warning in the first place. If someone starts work on this, feel free to have the actual warning text just be a lorem ipsum of some sort, I'll edit that later.

**Comment by drojf** [comment]
that sounds good, I'll try to prepare a template page for you to fill in.

also, I forgot about this: https://github.com/07th-mod/python-patcher/issues/197 " Show description of each group of mods on mod selection screen"

I don't think this warning interstitial would replace #197, so for now I'll just implement this warning page, ignoring #197, and do #197 later.

**Comment by andOlga** [comment]
The primary reason #197 exists is the Umineko patches in the first place tbh. I'm not sure if we need any sort of warnings on the Higurashi mods as they are up-to-date, feature-complete and (currently) the best way to play those games.

Although separating the mods by Higurashi/Umineko instead of by Question/Answer arcs would make a lot more sense, so at least that part remains relevant.

**Comment by drojf** [comment]
OK, I added a template to the [f-umineko-warning](branch https://github.com/07th-mod/python-patcher/compare/f-umineko-warning)

Just edit the "umineko-warning.html". I copy and pasted some HTML from other documents to make sure the table and bullet point formatting was still working, in case you want to use them.

If there any annoying css layout or other bugs, just ignore them. Just push it with any bugs to that baranch, let me know what the problems are, and I'll try to tidy it up later.

**Comment by andOlga** [comment]
I have pushed the relevant changes. The styles seem fine to me and it seems to function correctly overall. I will say that I have not tested this with the webview installer, only in-browser, so just saying that the link to the console patch site should open in an external browser, if any extra work needs to be done for that to happen.

I have also removed the old warnings as I believe this page alone is sufficient.

**Comment by drojf** [comment]
> so please ensure that the link to the console patch opens in an external browser

I just happened to do that anyway, but I didn't think about it in relation to the webview installer, so thanks for the reminder

I also separated the mods by Higurashi/Umineko while I was at it.

Once the new release is up I'll close this issue

**Comment by drojf** [comment]
Added in https://github.com/07th-mod/python-patcher/releases/tag/v1.2.17

**Comment by andOlga** [comment]
I didn't realize this during my initial testing, but it seems like these buttons here are not affected by the change. Could you please fix those?

![image](https://github.com/07th-mod/python-patcher/assets/462484/f2a5e253-7774-49fd-89df-50393f9103b5)

**Comment by drojf** [comment]
Oh, I can see how that happened... Yea I'll change those too

**Comment by drojf** [comment]
Should be fixed now as of https://github.com/07th-mod/python-patcher/tree/v1.2.18, see:

82e98298820595922da04831249292eabe416866
