### ISSUE TITLE
Higurashi UI and directory changes

### ISSUE THREAD

**Issue by ItaloKnox** [07th-mod/python-patcher#22]
We're rolling a new update for all UI packs in Higurashi, one of the changes is related to handling GOG releases in Tatarigoroshi/Meakashi and the other changes the filenames to avoid confusion and organize everything better. This change also includes sub-directory changes for all Higurashi files, though the filenames will remain the same for these files.

If needed, I can make a pull request with all the filename and directory changes. These changes need to be in place for the next release (web UI + old OST).

# New UI filename list
```
├── Himatsubushi-UI_steam_unix.7z
├── Himatsubushi-UI_steam_win.7z
├── Meakashi-UI_gog_win.7z
├── Meakashi-UI_steam_unix.7z
├── Meakashi-UI_steam_win.7z
├── Onikakushi-UI_steam_unix.7z
├── Onikakushi-UI_steam_win.7z
├── Tatarigoroshi-UI_mg_unix.7z
├── Tatarigoroshi-UI_mg_win.7z
├── Tatarigoroshi-UI_steam_unix.7z
├── Tatarigoroshi-UI_steam_win.7z
├── Tsumihoroboshi-UI_steam_unix.7z
├── Tsumihoroboshi-UI_steam_win.7z
├── Watanagashi-UI_steam_unix.7z
└── Watanagashi-UI_steam_win.7z
```

# UI filename changes

``%chapterName%-UI.7z`` becomes ``%chapterName%-UI_steam_win.7z``
``%chapterName%-UI_UNIX.7z`` becomes ``%chapterName%-UI_steam_unix.7z``
``%chapterName%-UI_MG.7z`` becomes ``%chapterName%-UI_mg_win.7z``
``%chapterName%-UI_UNIX-MG.7z`` becomes ``%chapterName%-UI_mg_unix.7z``
``%chapterName%-UI_GOG.7z`` becomes ``%chapterName%-UI_gog_win.7z``

# Tatarigoroshi and Meakashi instructions

* Tatarigoroshi **on GOG** now needs to install Steam's UI (might be addressed naturally in the Python installer)
* Meakashi **on GOG** now uses a new pack exclusive to the platform
    * ``Meakashi-UI_gog_win.7z``

# Sub-directory changes

Since Higurashi has a massive amount of files, I made copies of everything to new folders. That means the downloads still work in their original folders while we don't push these changes.

Should be pretty straightforward:

* ``*-CG`` and ``-CGAlt`` files go into ``/graphics``
* ``*-Voices`` files go into ``/voice``
* ``-Movies`` files go into ``/video``
* The old OST (``*-OldBGM``) and SE (``*-OldSE``) are in ``/audio`` [issue #16]
* ``*-UI`` files go into ``/ui``

The only thing needed is to append the new directory before the filename in the link.

**Comment by enumag** [comment]
I'm writing a PHP script to handle the UI urls. Instead of the above the installer should use an URL like this:

```
http://07th-mod.com/ui.php?chapter=onikakushi&os=win&platform=steam
where
os=win/unix
platform=steam/mg/gog
```

The script will send a redirect to the correct UI. This way the server will be able detect the availability of a custom pack for specific chapter+os+platform and decide which pack is appropriate.

**Comment by drojf** [comment]
I'm fine with doing this - I just wanna make sure you know we have (mostly) a system to handle different os and unity versions (but the platform is only steam/non-steam atm, so that part would need to be updated):

In https://github.com/07th-mod/python-patcher/blob/master/installData.json :
```
"fileOverrides" : [
    {"name": "movie",   "os": ["linux", "mac"], "steam": null,  "url":"https://07th-mod.com/rikachama/video/Tatarigoroshi-Movie_UNIX.7z"},
    {"name": "ui",      "os": ["windows"], 	    "unity": "5.4.0f1", "url":"https://07th-mod.com/rikachama/ui/Tatarigoroshi-UI_steam_win.7z"},
    {"name": "ui",      "os": ["windows"], 	    "unity": "5.3.4p1", "url":"https://07th-mod.com/rikachama/ui/Tatarigoroshi-UI_mg_win.7z"},
    {"name": "ui",      "os": ["linux", "mac"], "unity": "5.4.0f1", "url":"https://07th-mod.com/rikachama/ui/Tatarigoroshi-UI_steam_unix.7z"},
    {"name": "ui",      "os": ["linux", "mac"], "unity": "5.3.4p1", "url":"https://07th-mod.com/rikachama/ui/Tatarigoroshi-UI_mg_unix.7z"}
]
```

@tellowkrinkle might have some comments on this too

The installer doesn't need to be re-released each time it changes as the JSON file is always downloaded from the net.

**Comment by tellowkrinkle** [comment]
We should update the URLs to not include words like "steam" or "mg" but I think the current system works fine

**Comment by drojf** [comment]
I'm 95% sure this issue can be closed now. Enumag's PHP script is in service, and we use URLs like:

`https://07th-mod.com/ui.php?chapter=meakashi&os=unix&unity=5.5.3p1`

in the `installlData.json` for the UI downloads.

Please reopen if this isn't closed yet.
