### ISSUE TITLE
Installer Python Issues

### ISSUE THREAD

**Issue by tofuisnothere** [07th-mod/python-patcher#221]
Whenever I tried to install Umineko mod, it kept telling me python installer failed (see screenshot image) which I don't understand since I've installed python-3.12.0-amd64.
![Screenshot (825)](https://github.com/07th-mod/python-patcher/assets/152068445/03edd9c0-fad0-486f-9647-04117687581b)

Please kindly help,
Thank you.

**Comment by drojf** [comment]
Can you try the "no launcher" version of the installer? 

<https://github.com/07th-mod/python-patcher/releases/download/v1.2.22/07th-Mod.Installer.Windows.NoLauncher.zip>

Extract the .zip file to your desktop or downloads folder (NOT program files or the game root, as this may cause permissions issues)

Double click on the install.bat file.

A terminal will open, followed by a special page in your web browser (you use this webpage to install the mod).

If the install.bat does not work, close the terminal, then double click the install_safe_mode.bat for the text-only installer

**Comment by tofuisnothere** [comment]
I tried the no launcher version, clicked the install.bat file, and it launched to my browser page like this:
![Screenshot (827)](https://github.com/07th-mod/python-patcher/assets/152068445/6fa32b17-5afa-4187-93ec-21b3573f281a)


Do I need a VPN to open this?
Thank you.

**Comment by drojf** [comment]
> Do I need a VPN to open this?

No, everything runs locally on your machine at this stage, so it should just work.

----

**Can you try running the `install_safe_mode.bat` file? Then take a screenshot of the console window that pops up (I'm assuming there will still be an error/problem, but I want to see what it says).**

----

At this stage, I'm 99% sure it is an error running python. However, normally if there's a python error, it will show some sort of error message, but I couldn't see any on your initial post. I don't think I've seen this kind of problem before.

Did you notice any pop-ups or error messages when you ran the installer?

I can think of the following issues so far:
 - You're missing the "[Visual C++ Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=52685)" - click the link to download and install it. Our launcher is supposed to tell you to install it, though.
 - Your antivirus software is blocking python from running. Do you have any additional antivirus software on your computer?
 - Some other problem specific to your computer

----

If I can't resolve the issue, you can still install manually. Or, if you have another computer available, you can install the game and mod on there using the installer, then copy the game files onto your desired computer.

**Comment by tofuisnothere** [comment]
I uninstalled my additional antivirus software (It was SmadAV) and it worked!
![Screenshot (830)](https://github.com/07th-mod/python-patcher/assets/152068445/f506797b-023b-425c-bcaf-90c9474c61bd)

Now I can finally read Umineko which has been sitting in my Steam library for months (Hopefully, currently I'm still downloading the mods required).
![Screenshot (831)](https://github.com/07th-mod/python-patcher/assets/152068445/3a4e67eb-04bf-4cae-b755-0ab256979106)

Thank you for your help, I really appreciate it.

**Comment by drojf** [comment]
Glad you got it working.

I've added a item to the installer FAQ for this kind of issue: https://07th-mod.com/wiki/Installer/faq/#web-ui-does-not-appear-and-python-installer-failed-or-no-error-message-printed
