### ISSUE TITLE
What is Console Arcs?

### ISSUE THREAD

**Issue by K14Mua** [07th-mod/python-patcher#222]
I bought all the cicada games on Steam

- Higurashi When They Cry Hou - Ch.1 Onikakushi
- Higurashi When They Cry Hou - Ch.2 Watanagashi
- Higurashi When They Cry Hou - Ch.3 Tatarigoroshi
- Higurashi When They Cry Hou - Ch.4 Himatsubushi
- Higurashi When They Cry Hou - Ch. 5 Meakashi
- Higurashi When They Cry Hou - Ch.6 Tsumihoroboshi
- Higurashi When They Cry Hou - Ch.7 Minagoroshi
- Higurashi When They Cry Hou - Ch.8 Matsuribayashi
- Higurashi When They Cry Hou - Rei
- Higurashi When They Cry Hou+

Now I'm reading chapter 8, putting the puzzle together. But what does Console Arcs mean? Is this some kind of separate game that is not on Steam? Can I buy it somewhere and what is it?

**Comment by andOlga** [comment]
GitHub issues are not for support. Please direct these type of questions to our Discord.
