### ISSUE TITLE
Release of the python patcher

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#23]
- [x] need to fix 'choose manually' on mac/(linux?)?
- [x ] need to fill in the news in the https://github.com/07th-mod/python-patcher/tree/master/news folder (not necessary, but installer will silently error and not display any news for games without news) **edit: added dummy news for each game**
- [x] need to update JSON with new URLs (@ItaloKnox ?)
- [x] fix confirmation screen appearance and implementation properly
- [x] display and add description for each submod
- [x] ~when install starts, I have chosen to not hide the previous panels. This is not aesthetically pleasing. Either do this or have another button on the left hand side for "install status" and put the install status inside the right hand side panel, instead of just stacked ontop.~ EDIT: I've gotten used to it now, it actually seems OK. Maybe leave this until someone actually wants it changed

#### Optional
- [ ] fix jumping navbar

**Comment by tlm-2501** [comment]
A few issues:
- the lack of news cause an `undefined` pop-up when navigating to the installer page
- Umineko installers default to the voice-only patch

**Comment by drojf** [comment]
The jumping navbar is the only issue remaining. I don't really consider this a problem so I'm closing this issue. A new issue can be opened for that, if need be.
