### ISSUE TITLE
Feedback on new installer

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/python-patcher#37]
@drojf @ItaloKnox and anyone else interested, I tried running the new installer for the first time today.  Everything installed just fine, but I do have some suggestions:

1. The installer didn't auto-detect the installation directory (not sure if the new one supports that?) and the page doesn't actually tell you what installation path you need to select.  I was trying to tell it to use the HigurashiEp04Data folder and it wasn't working because I didn't realize I was actually supposed to select the executable.  It would help to note that above/below this box.

**Added a note below the box about what files you're supposed to choose when selecting manually**

2. The color on the "Start the Installation" button is too similar to the background color, at least on my monitor, so it's hard to tell that it's actually a clickable button.  The "choose install path" button has the same problem, too.  I suggest making them the same green as the Full Patch button up above.

![image](https://user-images.githubusercontent.com/20390474/57257612-f4867a00-7027-11e9-901c-2a68ac5877bb.png)

**buttons are now all green. When mouseovered, they become yellow, when selected they become orange**

3. The text in the "This option combines all the patches..." makes more sense for the main series patches, so it can probably be reworded to talk about the features specific to the console arcs release here.  I'll try to write something up for this.

3. We can probably just omit the Choose Mod Options section if there are no options to display.

**choose mod options doesn't show if no options to display**

4. This is purely cosmetic and really just a nitpick.  Overall progress reaches 100%, but the subtask progress didn't update to 100.
![image](https://user-images.githubusercontent.com/20390474/57257499-9fe2ff00-7027-11e9-99e8-8b0d17ed7f7c.png)

**subtask forced to 100% if overall is 100%**

5. Once we push the next release, we should update the blurb on the top of the index page to say New chapter: Tokihogushi-hen

**done**

**Comment by Adam-M93** [comment]
I have a couple suggestions myself regarding the new installer, first is regarding this "console arcs" text on the index page
![2019-05-07_00-23-00](https://user-images.githubusercontent.com/8584772/57261264-08999e00-705f-11e9-8301-3bfd39ed4ca1.png)
I personally find it a little hard to read, so I suggest either giving the text an outline/shadow, or making the background image darker, like with 
```
.background-image-holder.fadeIn
{ -webkit-filter: brightness(50%); filter: brightness(50%) }
```

![2019-05-07_00-32-55](https://user-images.githubusercontent.com/8584772/57261448-bf961980-705f-11e9-992f-8d29730f7643.png)

My second suggestion is an optional dark mode, and have your choice of light/dark mode be saved between versions, I'm not sure how to do this. Alternatively, or maybe along with the previously dark mode option, a custom style that could be loaded if present, like adding something like
```
<link href="custom_style.css" rel="stylesheet" type="text/css" media="all" />		
```
to the end of the list css files to be loaded, and if detected it loads the css from there on top of the others like 
![2019-05-07_00-17-01](https://user-images.githubusercontent.com/8584772/57261603-506cf500-7060-11e9-9831-09d32012b52e.png)

**Comment by DoctorDiablo** [comment]
One more thing:

Can you make it so that the voice and graphics patch file is the last one extracted?  Sometimes we throw an image or something in there because it's easier than updating the huge archives.  As long as the zip is extracted last, that version should override any other version of the same file.

**Comment by ItaloKnox** [comment]
Yeah, that should be true for all Higurashi chapters. The patch zip should always go last.

**Comment by drojf** [comment]
@DoctorDiablo I addressed all your issues - edited your comment with my comments in **bold** except:

> 3. The text in the "This option combines all the patches..." makes more sense for the main series patches, so it can probably be reworded to talk about the features specific to the console arcs release here.  I'll try to write something up for this.

I created an issue for this one here: https://github.com/07th-mod/python-patcher/issues/56

@Adam-M93  I added all your graphical changes in
