### ISSUE TITLE
Issue with console arcs system files

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/python-patcher#40]
@tellowkrinkle @drojf @ItaloKnox 

Someone on discord reported an issue where the system crashes on startup after installing the latest console arcs patch.  Turns out the new globalgamemanagers asset file based on the Linux version works on _some_ windows machines but not all of them, but the old windows did work for this user.

So to fix this, we need to split ConsoleArcs-System into separate archives by OS, one for Win and one for Mac/Linux.  I pushed two .7zs to the dev folder on the server for that (and also took this opportunity to remove the windows exe from the unix archive, since it only applies on windows).  So now we need to update the installer to use the right one based on your OS, then push the archives to rikachama.

**Comment by drojf** [comment]
I made the changes to URLs in installData.json as per the above commit, and tested that the windows and unix URLs actually downloaded and could be extracted. 

I didn't check that the game actually runs correctly (I just made it download the two URLs and not all the other files.)
