### ISSUE TITLE
Install full patch button doesn't do anything - left hand side 'Choose Mods' buttons are confusing

### ISSUE THREAD

**Issue by enumag** [07th-mod/python-patcher#43]
Selected a chapter to install and since I didn't care about any options I just clicked the button on the left to install. Nothing happened. Most likely because I had no path set. Maybe the button should be disabled or something until it can be used.

**Comment by drojf** [comment]
'tabs' (buttons) on the left hand side to select each submod are confusing. 

The style makes them look like buttons, but they are actually tabs.

**Comment by drojf** [comment]
The latest installer https://github.com/07th-mod/python-patcher/commit/f20d347d1dd4108ee6fd8ecdac5e8cbfa6b8a7bd doesn't have the left hand side menu anymore which should reduce confusion with submod selection.
