### ISSUE TITLE
Installation path is hidden under the optional stuff

### ISSUE THREAD

**Issue by enumag** [07th-mod/python-patcher#44]
Since installation path is required it should be the first thing on the page. Right now I couldn't even see it without scrolling down and that's on a 1440p monitor.

**Comment by drojf** [comment]
The idea was that we would encourage users to see/choose the available install options before they are allowed to start the install (in case they just select the game and immediately start the install without choosing options). 

If that's not a worry then I can move it to the top, just below the description of the mod.
