### ISSUE TITLE
Links on top right dont work

### ISSUE THREAD

**Issue by enumag** [07th-mod/python-patcher#55]
The links under "more" don't work at the moment. Perhaps consider removing them for the first public "stable" of the installer.

For context we have everything ready for the next set of Higurashi patches with quite significant changes (enough to call it another major release). The only thing we're waiting for is the installer to be in a "useable" state without too obvious bugs.

**Comment by drojf** [comment]
to be honest I never have clicked on that, it was part of the mockup italo gave me but I never filled it in. I'll just remove it

**Comment by drojf** [comment]
Should be fixed in https://github.com/07th-mod/python-patcher/commit/f7846ccb35a54b937a84fe4c52900458c4ee7ef8
