### ISSUE TITLE
Higurashi Changelogs need writing

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#57]
The changelog markdown files are operational, but the higurashi changelogs have not been filled in. They just have some placeholder text.

The markdown files are stored in the following git folder: https://github.com/07th-mod/python-patcher/tree/master/news . They are dynamically fetched from the installer each time it runs.

Please copy the example from https://github.com/07th-mod/python-patcher/blob/master/news/Umineko%20Question%20(Ch.%201-4).md as there are certain things you need to do to ensure it looks correct (like include #Changelog at the top of the file).

**Comment by drojf** [comment]
I'll just copy the latest release description for each chapter for now.

**Comment by enumag** [comment]
I gave the changelogs for the upcoming release to @ItaloKnox a while back. Maybe we should use those since they will be released soon (as soon as the installer is considered "finished").

**Comment by drojf** [comment]
We now redirect to the Higurashi releases page for each game instead of showing changelogs from the installer, so this issue isn't relevant anymore.
