### ISSUE TITLE
Github LFS Depreciation

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#66]
We have used the free tier of github LFS to store some of the files required for the patcher. Recently we got an email saying we used all the Bandwidth (1GB), and 130mb/1GB of the Storage.

Github LFS is only used to store the files in the "Bootstrap" folder, which nearly never change - we could easily zip up those files and store them on our main server instead.

This would require:
- zipping up the bootstrap file and uploading it to the server
- updating the travis build script to obtain the bootstrap files from the server each time

**Comment by tlm-2501** [comment]
After some discussion, it was decided to simply store these files in Git (non-LFS) as they are actually fairly small. This has now been done and LFS should no longer be in use. Though storage still won't be reclaimed -- as it seems that there is [no way to completely remove LFS objects from GitHub](https://help.github.com/en/articles/removing-files-from-git-large-file-storage#git-lfs-objects-in-your-repository), it should solve our main issue which is bandwidth breaking our automated builds.
