### ISSUE TITLE
Installer crashes if error occurs on startup

### ISSUE THREAD

**Issue by ccrowles** [07th-mod/python-patcher#74]
Hi, I'm very sorry to bother, but the installer won't launch. It gets stuck at [this](https://i.imgur.com/mrIeT1S.jpg) screen, and then closes itself. The log says:

> > Install Started On 2019-09-12 13:30:02.323646
> Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)]
> Installer Build Information: Build Date: 2019-08-21 13:35:51.907653
> Git Tag (Version): v0.0.76
> 
> Installer is being run from: [C:\Users\KiraV\Downloads\07th-mod_installer]
> Traceback (most recent call last):
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\urllib\request.py", line 1317, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\http\client.py", line 1229, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\http\client.py", line 1275, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\http\client.py", line 1224, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\http\client.py", line 1016, in _send_output
>     self.send(msg)
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\http\client.py", line 956, in send
>     self.connect()
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\http\client.py", line 928, in connect
>     (self.host,self.port), self.timeout, self.source_address)
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\socket.py", line 727, in create_connection
>     raise err
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\socket.py", line 716, in create_connection
>     sock.connect(sa)
> TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main.py", line 77, in <module>
>     check07thModServerConnection()
>   File "main.py", line 68, in check07thModServerConnection
>     testFile = urlopen(Request("http://07th-mod.com/", headers={"User-Agent": ""}))
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\urllib\request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\urllib\request.py", line 525, in open
>     response = self._open(req, data)
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\urllib\request.py", line 543, in _open
>     '_open', req)
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\urllib\request.py", line 503, in _call_chain
>     result = func(*args)
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\urllib\request.py", line 1345, in http_open
>     return self.do_open(http.client.HTTPConnection, req)
>   File "C:\Users\KiraV\Downloads\07th-mod_installer\python\lib\urllib\request.py", line 1319, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

Can anyone help?

**Comment by drojf** [comment]
I think the install loading screen (`loading_screen.html`) now displays any errors that occur on startup, so this issue can be closed.
