### ISSUE TITLE
Installer can't detect if game was partially uninstalled through steam

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#93]
The installer can't detect if the game is uninstalled through steam (if it's uninstalled but keeps the `installedVersionData.json` file). For example if you do:

1. Install game through steam (or using MG installer)
2. Install the mod (version files saved at this point)
3. Uninstall the game via steam/MG installer
4. Re-install the game via steam/MG installer
5. Try to re-install the mod

The game will still think the mod is "fully installed" because the version file is still there. 

I guess checking if the date-modified of some key files is newer than the date-modified of the `installedVersionData.json` might work, but if anyone has suggestions on how to check for this please let me know.

**Comment by ItaloKnox** [comment]
Okay, so here's what I managed to come up with:

1- Install game through steam (or using MG installer)
    * game ``.exe`` will pretty much *always* have the modification date before the installation date
2- Install the mod (version files saved at this point)
    * Installer touches the .exe and modifies the date to the current installation date
3- Uninstall the game via steam/MG installer
    * touched .exe will be removed
4- Re-install the game via steam/MG installer
    * untouched .exe will be added
5- Try to re-install the mod
    * installer compares the current .exe to the date it keeps stored in a local file (``installedVersionData.json``?)

I chose the game ``.exe`` as the example for that but it could be anything. Maybe the ``mainData`` file? I think there's a very low chance of it being "flagged" by mistake.

**Comment by drojf** [comment]
I'll go with this method for now (well, when I get around to it), we can change the method later anyway if there's a more suitable one

**Comment by drojf** [comment]
This feature has been in the installer for a long time and seems to work most of the time.

Since it just shows a warning message, it isn't too problematic if there is a false positive.
