### ISSUE TITLE
Slow installer startup time

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#94]
I noticed that the installer takes a while to start up. This is mainly made up of the following:
- scanForExecutables() function:
    - if a valid CURL is on the system, it does a dry run download of the 07th-mod website
    - if a valid Aria2c is on the system, it does a dry run download of the 07th-mod website 
- check07thModServerConnection() function:
    - this function does a test download of the 07th-mod website. it uses urlopen, or aria2c as a fallback on MacOS with SSL problems

The delay is noticeable because it's the delay between you pressing the "launch install" button and the actual installer appearing in your browser. each download adds about 2 seconds to the startup time.

If we were using python 3 I would make it execute all these operations concurrently using async/await, but I think it would be a bit difficult to maintain python 2/3 comparability at the same time.

Alternatively, the CURL and Aria2c checks could be less robust and just call '--help' to see that the .exes can run with a valid return code.

For now I'm not going to take any action, as it's a relatively minor problem.

**Comment by tellowkrinkle** [comment]
You can use threading instead
Only issue is that annoyingly `sys.exit` (which we use in check07thModServerConnection) throws an exception that exits the current thread, not the whole process

One solution would be to modify threads to catch exceptions and rethrow them on join like this
```py
def makeThread(target):
	def _target():
		try:
			t.result = target()
		except BaseException as exc:
			t.failure = exc
	t = threading.Thread(target=_target)
	join = t.join
	def _join():
		join()
		if hasattr(t, "result"):
			return t.result
		else:
			raise t.failure
	t.join = _join
	return t
```

Then you can do
```py
t1 = makeThread(scanForExecutables)
t2 = makeThread(check07thModServerConnection)
t1.start()
t2.start()
t1.join()
t2.join()
```
